<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260105105438 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates game, player, thing tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code UUID NOT NULL, status VARCHAR(20) NOT NULL, things_per_player SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, current_thing_id INT DEFAULT NULL, master_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318C77153098 ON game (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318C5E117C8D ON game (current_thing_id)');
        $this->addSql('CREATE INDEX IDX_232B318C13B3DB11 ON game (master_id)');
        $this->addSql('CREATE TABLE game_player (game_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (game_id, player_id))');
        $this->addSql('CREATE INDEX IDX_E52CD7ADE48FD905 ON game_player (game_id)');
        $this->addSql('CREATE INDEX IDX_E52CD7AD99E6F5DF ON game_player (player_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, telegram_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE thing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, game_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B4C2C83E48FD905 ON thing (game_id)');
        $this->addSql('CREATE INDEX IDX_5B4C2C83F675F31B ON thing (author_id)');
        $this->addSql('CREATE TABLE thing_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score SMALLINT NOT NULL, thing_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6925C968C36906A7 ON thing_rating (thing_id)');
        $this->addSql('CREATE INDEX IDX_6925C96899E6F5DF ON thing_rating (player_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6925C968C36906A799E6F5DF ON thing_rating (thing_id, player_id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C5E117C8D FOREIGN KEY (current_thing_id) REFERENCES thing (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C13B3DB11 FOREIGN KEY (master_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT FK_E52CD7ADE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT FK_E52CD7AD99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE thing ADD CONSTRAINT FK_5B4C2C83E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thing ADD CONSTRAINT FK_5B4C2C83F675F31B FOREIGN KEY (author_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thing_rating ADD CONSTRAINT FK_6925C968C36906A7 FOREIGN KEY (thing_id) REFERENCES thing (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thing_rating ADD CONSTRAINT FK_6925C96899E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C5E117C8D');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C13B3DB11');
        $this->addSql('ALTER TABLE game_player DROP CONSTRAINT FK_E52CD7ADE48FD905');
        $this->addSql('ALTER TABLE game_player DROP CONSTRAINT FK_E52CD7AD99E6F5DF');
        $this->addSql('ALTER TABLE thing DROP CONSTRAINT FK_5B4C2C83E48FD905');
        $this->addSql('ALTER TABLE thing DROP CONSTRAINT FK_5B4C2C83F675F31B');
        $this->addSql('ALTER TABLE thing_rating DROP CONSTRAINT FK_6925C968C36906A7');
        $this->addSql('ALTER TABLE thing_rating DROP CONSTRAINT FK_6925C96899E6F5DF');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_player');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE thing');
        $this->addSql('DROP TABLE thing_rating');
    }
}
